version: "3.8"

services:
  db:
    env_file:
      - .env
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    env_file:
      - .env
    build: .
    environment:
      - API_PORT=${API_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "80:${API_PORT}"

volumes:
  pgdata:

