name: Deploy simple-api

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: List SSH keys in agent 🔑
        run: ssh-add -l

      - name: Test SSH connection 👀
        run: ssh -o StrictHostKeyChecking=no -v ubuntu@${{ secrets.EC2_HOST }} exit

      - name: Deploy na EC2 🚀
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} '
            sudo chown -R ubuntu:ubuntu /dev/simple-api &&
            cd /dev/simple-api/simple-api &&
            git pull &&
            git config --add safe.directory /dev/simple-api/simple-api &&
            sudo docker system prune -af &&
            sudo docker-compose down &&
            sudo docker-compose up -d --build
          '
