n      - name: Deploy na EC2 🚀
        run: |
          # 1) Ajustar permissões da pasta antes do sync
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/id_rsa \
            ubuntu@${{ secrets.EC2_HOST }} \
            "sudo chown -R ubuntu:ubuntu /dev/simple-api"

          # 2) Sincronizar código via rsync rodando como sudo no destino
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
            --rsync-path="sudo rsync" \
            $GITHUB_WORKSPACE/ \
            ubuntu@${{ secrets.EC2_HOST }}:/dev/simple-api/simple-api/

          # 3) Rodar deploy remoto
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/id_rsa \
            ubuntu@${{ secrets.EC2_HOST }} \
            "cd /dev/simple-api/simple-api && \
             sudo docker system prune -af && \
             sudo docker-compose down && \
             sudo docker-compose up -d --build"
