name: Deploy simple-api

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: List SSH keys in agent 🔑
        run: ssh-add -l

      - name: Test SSH connection 👀
        run: |
          ssh -o StrictHostKeyChecking=no -v \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            exit

     - name: Deploy na EC2 🚀
     run: |
       ssh -o StrictHostKeyChecking=no \
         -i ~/.ssh/id_rsa \
         ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
         "cd /dev/simple-api/simple-api && \
          git config --global --add safe.directory /dev/simple-api/simple-api && \
          sudo docker system prune -af && \
          sudo docker-compose down && \
          sudo docker-compose up -d --build"

