name: Deploy simple-api

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy na EC2 🚀
        run: |
          # 1) Sincroniza todo o repositório para o EC2
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
            $GITHUB_WORKSPACE/ ubuntu@${{ secrets.EC2_HOST }}:/dev/simple-api/simple-api/

          # 2) Roda o deploy remoto
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            ubuntu@${{ secrets.EC2_HOST }} \
            "sudo chown -R ubuntu:ubuntu /dev/simple-api && \
             cd /dev/simple-api/simple-api && \
             sudo docker system prune -af && \
             sudo docker-compose down && \
             sudo docker-compose up -d --build"
