name: Deploy simple-api

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: List SSH keys in agent 🔑
        run: ssh-add -l

      - name: Test SSH connection 👀
        run: ssh -o StrictHostKeyChecking=no -v ubuntu@${{ secrets.EC2_HOST }} exit

      - name: Deploy na EC2 🚀
        run: |
          # Ajusta dono para permitir escrita
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/id_rsa \
            ubuntu@${{ secrets.EC2_HOST }} \
            "sudo chown -R ubuntu:ubuntu /dev/simple-api"

          # Sincroniza código com sudo no destino
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
            --rsync-path="sudo rsync" \
            $GITHUB_WORKSPACE/ \
            ubuntu@${{ secrets.EC2_HOST }}:/dev/simple-api/simple-api/

          # Roda deploy: limpa, desce e sobe containers
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/id_rsa \
            ubuntu@${{ secrets.EC2_HOST }} \
            "cd /dev/simple-api/simple-api && \
             sudo docker system prune -af && \
             sudo docker-compose down && \
             sudo docker-compose up -d --build"
